name: Build And Test

on: [push]

jobs:
  build:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        #os: [windows-2019]
        BUILD_TYPE: [RelWithDebInfo, Debug]
        include: 
          - CONAN_BUILD_TYPE: Debug
            BUILD_TYPE: Debug
          - CONAN_BUILD_TYPE: Release
            BUILD_TYPE: RelWithDebInfo

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with: 
          version: 1.59.0
      
      - name: Detect Conan Profile
        run: conan profile new default --detect
      
      - name: Fix libcxx setting
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
        if: matrix.os == 'ubuntu-latest'
    
      - name: Install Dependencies
        run: conan install --install-folder ${{github.workspace}}/build -s build_type=${{matrix.CONAN_BUILD_TYPE}} -o sqlite3:shared=True .
        #run: conan install --install-folder ${{github.workspace}}/build -s build_type=${{matrix.CONAN_BUILD_TYPE}} .

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DBUILD_SHARED_LIBS=True
        #run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{matrix.BUILD_TYPE}} --output-on-failure